base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
  rhods-addon-tests:
    name: ods-ci
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: smoke-rosa-rhods-addon-baseline-fips
  cron: 0 0 1 1 *
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      INSTALL_FROM_IIB: "true"
      OPENSHIFT_VERSION: "4.13"
    workflow: addons-and-operators-rhods-interop-aws-rosa
zz_generated_metadata:
  branch: rhods-addon-interop
  org: CSPI-QE
  repo: MSI
  variant: v4.13-IIB
