base_images:
  cli:
    name: "4.12"
    namespace: ocp
    tag: cli
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
  rhods-addon-tests:
    name: ods-ci
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: rhods-tests
  cron: 0 12 * * 6
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      ADDON1_CONFIG: managed-odh|notification-email=interop-qe-ms@redhat.com
      COMPUTE_MACHINE_TYPE: m5.4xlarge
      DISABLE_WORKLOAD_MONITORING: "false"
      ENABLE_AUTOSCALING: "false"
      ETCD_ENCRYPTION: "true"
      MAX_REPLICAS: "6"
      MIN_REPLICAS: "3"
      MULTI_AZ: "true"
      REPLICAS: "6"
      TIMEOUT: "7200"
    post:
    - ref: addon-uninstall
    - ref: rosa-sts-cluster-deprovision
    - ref: rosa-sts-account-roles-delete
    pre:
    - ref: rosa-sts-account-roles-create
    - ref: rosa-sts-cluster-provision
    - ref: rosa-conf-idp-htpasswd
    - ref: osd-ccs-conf-idp-htpasswd-multi-users
    - ref: rosa-operators-wait-ready
    - ref: addon-install
    test:
    - ref: addon-test-rhods
zz_generated_metadata:
  branch: rhods
  org: CSPI-QE
  repo: MSI
