base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
images:
- dockerfile_literal: |
    FROM python:3
    WORKDIR /usr/src/app
    ENTRYPOINT ["echo", "PYTHON-ENTRYPOINT!"]
  to: msi-python
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: msi-test-steps
  cron: 0 0 1 1 *
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      TEST_ENV_VAR: omrirh-env-var
    test:
    - ref: msi-test-step
    workflow: rosa-aws-sts
zz_generated_metadata:
  branch: main
  org: CSPI-QE
  repo: MSI
