base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: addon-aws-ipi-qetest
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      OPENSHIFT_VERSION: "4.13"
      OPERATOR1_CONFIG: name=rhods-operator;namespace=redhat-ods-operator
    workflow: addon-aws-ipi
