base_images:
  cli:
    name: "4.12"
    namespace: ocp
    tag: cli
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
  rhods-addon-tests:
    name: ods-ci
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.12"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: smoke-osd-rhods-addon-baseline-fips
  cron: 0 12 * * 6
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      ADDON1_CONFIG: name=managed-odh;notification-email=interop-qe-ms@redhat.com
      API_HOST: production
      COMPUTE_MACHINE_TYPE: g4dn.2xlarge
      FIPS: "true"
      OPENSHIFT_VERSION: "4.12"
      OPERATOR1_CONFIG: name=gpu-operator-certified;namespace=nvidia-gpu-operator;source=certified-operators;target-namespaces=nvidia-gpu-operator,
      OPERATOR2_CONFIG: name=servicemeshoperator
      OPERATOR3_CONFIG: name=serverless-operator;namespace=openshift-serverless
      OPERATOR4_CONFIG: name=openshift-pipelines-operator-rh;namespace=openshift-pipelines;channel=latest
      OPERATOR5_CONFIG: name=nfd;namespace=openshift-nfd;target-namespaces=openshift-nfd,
      PARALLEL: "false"
      COMPUTE_NODES: "2"
      OCM_LOGIN_ENV: production
    test:
    - ref: addon-tests-rhods
    workflow: addons-and-operators-aws-osd
- as: smoke-ipi-rhods-addon-baseline-fips
  cron: 0 12 * * 6
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      ADDON1_CONFIG: name=managed-odh;notification-email=interop-qe-ms@redhat.com
      API_HOST: production
      COMPUTE_NODE_TYPE: g4dn.2xlarge
      FIPS_ENABLED: "true"
      OPENSHIFT_VERSION: "4.12"
      OPERATOR1_CONFIG: name=gpu-operator-certified;namespace=nvidia-gpu-operator;source=certified-operators;target-namespaces=nvidia-gpu-operator,
      OPERATOR2_CONFIG: name=servicemeshoperator
      OPERATOR3_CONFIG: name=serverless-operator;namespace=openshift-serverless
      OPERATOR4_CONFIG: name=openshift-pipelines-operator-rh;namespace=openshift-pipelines;channel=latest
      OPERATOR5_CONFIG: name=nfd;namespace=openshift-nfd;target-namespaces=openshift-nfd,
      PARALLEL: "false"
      COMPUTE_NODE_REPLICAS: "2"
      # OCM_LOGIN_ENV: production  TODO: check how to set ocm env as prod
    test:
    - ref: addon-tests-rhods
    workflow: addons-and-operators-aws-ipi
