base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: sanity-aws-osd-rhods-addon
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      ADDON1_CONFIG: name=managed-odh;notification-email=interop-qe-ms@redhat.com
      COMPUTE_MACHINE_TYPE: m5.4xlarge
      COMPUTE_NODES: "6"
      OPENSHIFT_VERSION: "4.13"
    workflow: addon-aws-osd
zz_generated_metadata:
  branch: qe-test-addon
  org: CSPI-QE
  repo: MSI
  variant: v4.13-aws-osd
