base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
images:
- dockerfile_literal: |
    FROM quay.io/modh/ods-ci:latest
    WORKDIR /tmp/ods-ci
    ENTRYPOINT ["bash"]
  to: rhods-addon-tests
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: rhods-tests
  cron: 0 12 * * 6
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      ADDON_NAME: managed-odh
      ADDON_PARAMETERS: notification-email=interop-qe-ms@redhat.com
      COMPUTE_MACHINE_TYPE: m5.4xlarge
      REPLICAS: "6"
    test:
    - ref: addon-install
    - ref: addon-test-rhods
    - ref: addon-uninstall
    workflow: rosa-aws-sts
zz_generated_metadata:
  branch: rhods
  org: CSPI-QE
  repo: MSI
