base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: smoke-rosa-rhods-addon-baseline
  cron: 0 12 * * 6
  remote_api: true
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      CLUSTER_NAME: "ods-all-op-413"
      OPENSHIFT_VERSION: "4.13"
      COMPUTE_MACHINE_TYPE: "g4dn.2xlarge"
      REPLICAS: "2"
      ADDON1_CONFIG: "managed-odh|notification-email=interop-qe-ms@redhat.com"
      OPERATOR1_CONFIG: "gpu-operator-certified"
      OPERATOR2_CONFIG: "servicemeshoperator"
      OPERATOR3_CONFIG: "serverless-operator"
      OPERATOR4_CONFIG: "openshift-pipelines-operator-rh"
      OPERATOR5_CONFIG: "nfd"  # or openshift-nfd-operator ?
    post:
      - operator-uninstall
      - addon-uninstall
      - rosa-aws-sts-deprovision
    pre:
      - rosa-aws-sts-provision
      - addon-install
      - operator-install
    test:
      - addon-test-rhods