base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
  upi-installer:
    name: "4.13"
    namespace: ocp
    tag: upi-installer
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: sanity-aws-osd-rhods-operator
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      COMPUTE_MACHINE_TYPE: m5.4xlarge
      COMPUTE_NODES: "6"
      OPENSHIFT_VERSION: "4.13"
      OPERATOR1_CONFIG: name=rhods-operator;namespace=redhat-ods-operator
    workflow: operator-aws-osd
zz_generated_metadata:
  branch: rhods-operator
  org: CSPI-QE
  repo: MSI
  variant: v4.13-aws-osd
