base_images:
  rhods-addon-tests:
    name: ods-ci
    namespace: ci
    tag: latest
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: smoke-rosa-rhods-addon-baseline
  cron: 0 12 * * 6
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      ADDON1_CONFIG: name=managed-odh;notification-email=interop-qe-ms@redhat.com
      CLUSTER_NAME: ods-all-op-413
      COMPUTE_MACHINE_TYPE: g4dn.2xlarge
      OPENSHIFT_VERSION: "4.13"
      OPERATOR1_CONFIG: name=gpu-operator;namespace=nvidia-gpu-operator
      OPERATOR2_CONFIG: name=servicemeshoperator
      OPERATOR3_CONFIG: name=serverless-operator;namespace=openshift-serverless
      OPERATOR4_CONFIG: name=openshift-pipelines-operator-rh;namespace=openshift-pipelines;channel=latest
      OPERATOR5_CONFIG: name=nfd;namespace=openshift-nfd
      REPLICAS: "2"
    post:
    - ref: operator-uninstall
    - ref: addon-uninstall
    - chain: rosa-aws-sts-deprovision
    pre:
    - chain: rosa-aws-sts-provision
    - ref: addon-install
    - ref: operator-install
    test:
    - ref: addon-tests-rhods
zz_generated_metadata:
  branch: rhods-operator-interop
  org: CSPI-QE
  repo: MSI
  variant: v4.13