base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: qetest-addon-aws-osd
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      ADDON1_CONFIG: name=managed-odh;notification-email=interop-qe-ms@redhat.com
      OPENSHIFT_VERSION: "4.13"
    workflow: addon-aws-osd
- as: qetest-addon-aws-ipi
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      ADDON1_CONFIG: name=managed-odh;notification-email=interop-qe-ms@redhat.com
    workflow: addon-aws-ipi
zz_generated_metadata:
  branch: qe-test-addon
  org: CSPI-QE
  repo: MSI
  variant: v4.13
