base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
  upi-installer:
    name: "4.13"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: qetest-operator-aws-ipi
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      COMPUTE_NODE_REPLICAS: "6"
      OPENSHIFT_VERSION: "4.13"
      OPERATOR1_CONFIG: name=rhods-operator;namespace=redhat-ods-operator
    workflow: operator-aws-ipi
- as: qetest-operator-aws-osd
  steps:
    cluster_profile: aws-managed-cspi-qe
    env:
      COMPUTE_NODES: "6"
      OPENSHIFT_VERSION: "4.13"
      OPERATOR1_CONFIG: name=rhods-operator;namespace=redhat-ods-operator
    workflow: operator-aws-osd
zz_generated_metadata:
  branch: rhods-operator
  org: CSPI-QE
  repo: MSI
  variant: v4.13-aws-ipi-osd
