base_images:
  cli:
    name: "4.18"
    namespace: ocp
    tag: cli
  openshift-cli-installer:
    name: openshift-cli-installer
    namespace: ci
    tag: stable
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- context_dir: .
  dockerfile_path: ods_ci/build/Dockerfile_interop
  to: rhoai-tests
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.18"
resources:
  '*':
    limits:
      memory: 20Gi
    requests:
      cpu: 8000m
      memory: 10Gi
tests:
- as: rhoai-interop-aws-osd
  cron: 0 6 * * 1
  steps:
    cluster_profile: aws-managed-osd-rhoai-qe
    env:
      CLUSTER_NAME_PREFIX: rhoai
      CLUSTER1_CONFIG: platform=aws-osd;region=us-east-2;version=4.18;channel-group=stable;compute-machine-type=m5.4xlarge;timeout=3h;replicas=3;fips=false;ocm-env=stage
      OPERATORS: |
        [
            {"name": "authorino-operator", "source": "redhat-operators", "channel": "tech-preview-v1", "install_namespace": "openshift-operators"},
            {"name": "servicemeshoperator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators"},
            {"name": "serverless-operator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-serverless", "operator_group":"serverless-operator"}
        ]
      PULL_SECRET_NAME: pull-secret
      RHOAI_VERSION: 2.16.0
      S3_BUCKET_NAME: openshift-cli-installer
      S3_BUCKET_PATH: openshift-ci
    test:
    - ref: install-operators
    - ref: rhoai-ocm-install
    - ref: rhoai-deploy-dsc
    - ref: rhoai-tests
    workflow: cluster
- as: rhoai-interop-aws-rosa
  cron: 0 6 * * 1
  steps:
    cluster_profile: aws-managed-rosa-rhoai-qe
    env:
      CLUSTER_NAME_PREFIX: rhoai
      CLUSTER1_CONFIG: platform=rosa;region=us-east-2;version=4.18;channel-group=stable;compute-machine-type=m5.4xlarge;timeout=3h;replicas=3;fips=false;ocm-env=stage
      OPERATORS: |
        [
            {"name": "authorino-operator", "source": "redhat-operators", "channel": "tech-preview-v1", "install_namespace": "openshift-operators"},
            {"name": "servicemeshoperator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators"},
            {"name": "serverless-operator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-serverless", "operator_group":"serverless-operator"},
        ]
      PULL_SECRET_NAME: pull-secret
      RHOAI_VERSION: 2.16.0
      S3_BUCKET_NAME: openshift-cli-installer
      S3_BUCKET_PATH: openshift-ci
    test:
    - ref: install-operators
    - ref: rhoai-ocm-install
    - ref: rhoai-deploy-dsc
    - ref: rhoai-tests
    workflow: cluster
zz_generated_metadata:
  branch: release-2.16-fix
  org: red-hat-data-services
  repo: ods-ci
  variant: rhoai-ocp4.18-managed-interop
