base_images:
  cli:
    name: "4.16"
    namespace: ocp
    tag: cli
  rhoai-tests:
    name: ods-ci
    namespace: ci
    tag: dev
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.16"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: rhoai-interop-ibm
  cron: 0 0 11 6 *
  steps:
    cluster_profile: ibmcloud-cspi-qe
    env:
      BASE_DOMAIN: zstream.interop.ccitredhat.com
      FIREWATCH_CONFIG: |
        {
          "failure_rules":
            [
              {"step": "rhoai-tests", "failure_type": "test_failure", "classification": "RHOAI Test Failure", "jira_project": "RHODS", "group": {"name": "lp-tests", "priority": 3}, "jira_component": ["!default"], "jira_assignee": "!default", "jira_priority": "!default", "jira_additional_labels": ["!default","interop-tests"]}
            ]
        }
      FIREWATCH_CONFIG_FILE_PATH: https://raw.githubusercontent.com/CSPI-QE/cspi-utils/main/firewatch-base-configs/aws-ipi/lp-interop.json
      FIREWATCH_DEFAULT_JIRA_ADDITIONAL_LABELS: '["4.16-lp","self-managed-lp","rhoai-lp"]'
      FIREWATCH_DEFAULT_JIRA_ASSIGNEE: apodhrad@redhat.com
      FIREWATCH_DEFAULT_JIRA_COMPONENT: '["Customer Impact"]'
      FIREWATCH_DEFAULT_JIRA_PRIORITY: critical
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPINTEROP
      FIREWATCH_FAIL_WITH_TEST_FAILURES: "true"
      OPERATORS: |
        [
            {"name": "authorino-operator", "source": "redhat-operators", "channel": "tech-preview-v1", "install_namespace": "openshift-operators"},
            {"name": "servicemeshoperator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators"},
            {"name": "serverless-operator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-serverless", "operator_group":"serverless-operator"},
            {"name": "openshift-pipelines-operator-rh", "source": "redhat-operators", "channel": "latest", "install_namespace": "openshift-pipelines", "operator_group":"openshift-pipelines-operator"},
            {"name": "rhods-operator", "source": "redhat-operators", "channel": "stable-2.13", "install_namespace": "redhat-ods-operator", "operator_group":"rhods-ai-operator"}
        ]
    test:
    - ref: install-operators
    - ref: rhoai-deploy-dsc
    - ref: rhoai-tests
    workflow: firewatch-ipi-ibmcloud
zz_generated_metadata:
  branch: master
  org: red-hat-data-services
  repo: ods-ci
  variant: rhoai2.13-ocp4.16-lp-interop
