base_images:
  cli:
    name: "4.18"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- context_dir: .
  dockerfile_path: ods_ci/build/Dockerfile_interop
  to: rhoai-tests
releases:
  latest:
    prerelease:
      product: ocp
      version_bounds:
        lower: 4.18.0-0
        stream: 4-stable
        upper: 4.19.0-0
resources:
  '*':
    limits:
      memory: 20Gi
    requests:
      cpu: 8000m
      memory: 10Gi
tests:
- as: rhoai-interop-aws
  cron: 0 6 * * 1
  steps:
    cluster_profile: aws-managed-rosa-rhoai-qe
    env:
      COMPUTE_MACHINE_TYPE: m5.2xlarge
      FIREWATCH_CONFIG: |
        {
          "failure_rules":
            [
              {"step": "rhoai-tests", "failure_type": "test_failure", "classification": "RHOAI Test Failure", "jira_project": "RHODS", "group": {"name": "rhoai-tests", "priority": 3}, "jira_component": ["!default"], "jira_assignee": "!default", "jira_priority": "!default", "jira_additional_labels": ["!default","interop-tests"]}
            ]
        }
      FIREWATCH_CONFIG_FILE_PATH: https://raw.githubusercontent.com/CSPI-QE/cspi-utils/blob/main/firewatch-base-configs/rosa/lp-interop.json
      FIREWATCH_DEFAULT_JIRA_ADDITIONAL_LABELS: '["4.18-lp","rosa-managed","rhoai"]'
      FIREWATCH_DEFAULT_JIRA_COMPONENT: '["Customer Impact"]'
      FIREWATCH_DEFAULT_JIRA_PRIORITY: critical
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPINTEROP
      FIREWATCH_FAIL_WITH_TEST_FAILURES: "true"
      OPERATORS: |
        [
            {"name": "authorino-operator", "source": "redhat-operators", "channel": "tech-preview-v1", "install_namespace": "openshift-operators"},
            {"name": "servicemeshoperator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators"},
            {"name": "serverless-operator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-serverless", "operator_group":"serverless-operator"},
        ]
      REPLICAS: "3"
    test:
    - ref: install-operators
    - ref: rhoai-ocm-install
    - ref: rhoai-deploy-dsc
    - ref: rhoai-tests
    workflow: firewatch-rosa-aws-sts
zz_generated_metadata:
  branch: release-2.16
  org: red-hat-data-services
  repo: ods-ci
  variant: rhoai-ocp4.18-managed-rosa-interop
